# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9eefd1e89d0822f7d0ecc58775a4826a72678210a11613dc13d2021eea4e08f2e392a67171b23ba311294c54ff5e2389914a32aa4ea5acf1ad41630d00cad66

test:
  secret_key_base: a83b19da81e5ef8895acc3e8d69c55d942d54a1019ff3f15d27436b6146100f587c906d6705d7fb90ed96c27811e2584ae363bcf6e69fe120b9db7f58835272b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
